- index.html
- src/components/GameSchedule.tsx
- src/components/Highlight.tsx
- src/components/MainPostGroup.tsx
- src/components/MainPostList.tsx
- src/components/MainTitle.tsx
- src/components/Ranking.tsx
- src/css/global.css
- src/css/tailwind.css
- src/hooks/useDarkMode.ts
- src/layout/Header.tsx
- src/layout/RootLayout.tsx
- src/pages/FanPage.tsx
- src/pages/Home.tsx
- src/types/postType.ts
메인 페이지 디자인 개선
Header -> 다크모드 적용
메인 페이지 다크모드 적용
>
> Feat: 메인 페이지 다크모드 작업 및 기타 디자인 개선, 기능 추가

- src/components/FollowBox.tsx
- src/components/FollowCard.tsx
- src/components/ProfileHeader.tsx
> feat: 프로필 페이지 반응형 및 다크모드 적용

- src/App.tsx
- src/components/HeaderIcon.tsx
- src/components/NoticeBox.tsx
- src/components/UserMenu.tsx
- src/layout/Header.tsx
Header Icon 컴포넌트 분리 작업
아이콘 클릭 했을 때 메뉴 추가
> header 메뉴추가

- src/App.tsx
- src/layout/RootLayout.tsx
App.tsx route 정리
layout Footer 노출 조건 추가
>
> Fix: Router & layout

- src/components/Comments.tsx
- src/components/Sidebar.tsx
- src/components/SimpleProfileCard.tsx
- src/components/Threads.tsx
- src/pages/FanPage.tsx
팬페이지에 다크모드 적용했고 사이드바 끝까지 스크롤 했을 때 숨김 처리 수정했습니다.
> fix : Fan page 다크모드 적용 및 사이드바 수정

- src/pages/Home.tsx
> Fix: main 디자인 수정

- src/components/header/HeaderIcon.tsx
- src/components/header/NoticeBox.tsx
- src/components/header/SearchBox.tsx
- src/components/header/UserMenu.tsx
- src/layout/Header.tsx
header search부분 기능 진행중입니다.
gnb 로고 경로 수정 및 디자인 수정
상단 아이콘 토글 기능 개선
> feat: 검색기능 추가 

- src/components/Main/GameSchedule.tsx
경기 일정 디자인 수정
경기 일정이 없을떄 무한 스켈레톤 수정
>
> Fix: 경기 일정 디자인 수정

- src/layout/Header.tsx
- src/utils/getLogoImages.ts
> Fix: 데이터 병합

- src/components/FanPage/Threads.tsx
- src/components/FanPage/Upload.tsx
> feat: 게시물 수정 기능 추가

- src/components/Header/SearchBox.tsx
- src/components/Header/SearchThreads.tsx
- src/layout/Header.tsx
> feat: 스레드 검색기능 추가

- src/layout/Header.tsx
- src/pages/Home.tsx
> Fix: Header Link 수정

- src/components/Header/SearchBox.tsx
- src/components/Header/SearchThreads.tsx
- src/components/Header/SearchUser.tsx
- src/components/Header/UserRecommend.tsx
검색 박스와 user, thread 컴포넌트 분리
검색창에 랜덤으로 유저 추천 부분 추가 - 배치 및 디자인은 고민 중입니다.
> feat: 검색기능 컴포넌트 분리, 추천 유저 기능

- src/App.tsx
> Fix: App 경로 수정

- src/api/axiosInstance.ts
- src/api/login.ts
- src/components/Auth/AuthBoard.tsx
- src/components/Auth/AuthInput.tsx
- src/components/Auth/BlueBoard.tsx
- src/components/Auth/LogIn.tsx
- src/components/Main/MainPostList.tsx
- src/stores/useUserStore.ts
- src/types/userTypes.ts
로그인 기능 완성
Main JSON.parse 오류 수정
>
> Feat: Login 기능 완성, main 디자인 수정

- src/App.tsx
- src/components/Auth/LogIn.tsx
- src/components/Main/MainPostList.tsx
모든 페이지 다크모드 적용
로그인 시 아이디 저장 로직 추가
>
> Fix: 전체 페이지 다크모드 적용

- src/components/Header/SearchBox.tsx
- src/components/Header/SearchUser.tsx
- src/components/Header/ThreadRecommends.tsx
- src/components/Header/UserRecommend.tsx
탭 [유저 / 게시글 ] 추가
검색 키워드 입력 전, 빈칸 일 경우 유저 or 게시글 추천 목록 
유저 랜덤, 게시글 최신글 기준
> fix: 검색창 구조 변경

- src/App.tsx
> Fix: NotFound 경로 수정

- src/components/Header/SearchBox.tsx
- src/components/Header/SearchThreads.tsx
- src/components/Header/SearchUser.tsx
- src/components/Header/ThreadRecommends.tsx
- src/components/Header/UserRecommend.tsx
검색 결과에 유저/게시글 한번에 나오는 오류가 있어 수정했습니다.
검색 결과시 내용 넘치면 스크롤 생기도록 추가했습니다.
> fix: 검색 결과창 수정

- src/components/FanPage/Comments.tsx
- src/components/FanPage/Threads.tsx
- src/components/FanPage/ThreadsList.tsx
axiosInstance.ts로 api연동 및 로그인 계정 좋아요처리
> 로그인 계정과 일치하는 좋아요 처리

- src/components/Auth/AuthInput.tsx
- src/components/Auth/SignUp.tsx
state랑 같은 기능에 다른 이름으로 나눠져 있던 함수가 많아 하나의 함수 안에 해결 될 수 있도록 수정 했습니다. 
상윤님이 말씀 해주신대로 state랑 기능 겹치는 함수들 정리 해봤습니다
> signup 컴포넌트 리팩토링

- src/api/auth.ts
- src/api/axiosInstance.ts
- src/components/Header/UserMenu.tsx
- src/stores/userStore.ts
> Fix: store 오류 수정

- src/App.tsx
- src/components/message/InboxMessage.tsx
- src/components/message/MessageContainer.tsx
- src/components/message/MessageEditor.tsx
- src/components/message/SendButton.tsx
- src/components/message/SentList.tsx
- src/components/message/Toast.ts
- src/pages/MessagePage.tsx
- src/types/messageType.ts
message 컴포넌트 분리작업 중간 pr
app.tsx route 수정
> fix: 쪽지보내기, 답장하기 컴포넌트 분리

- src/components/FanPage/Button.tsx
- src/components/FanPage/Comments.tsx
- src/components/FanPage/Threads.tsx
- src/components/FanPage/ThreadsList.tsx
> Fix : 좋아요, 댓글 예외처리

- src/components/Main/GameSchedule.tsx
> Fix: Main 페이지 디자인 일부 수정

- src/App.tsx
- src/components/Main/Highlight.tsx
유튜브 썸네일 이미지 API 변경으로 인한 데이터 수정
>
> Fix: youtube 썸네일 사진 오류 수정

- src/App.tsx
- src/components/Profile/FollowBox.tsx
- src/components/Profile/FollowCard.tsx
> refactor: 팔로워 및 팔로잉 목록

- src/App.tsx
- src/components/Auth/EditProfile.tsx
- src/components/Auth/SignUp.tsx
- src/components/Auth/inputValidation.ts
- src/types/userTypes.ts
> editProfile input 유효성 검사

- src/components/Main/GameSchedule.tsx
- src/components/Main/Highlight.tsx
> Fix: 디자인 수정

- src/App.tsx
- src/components/Main/MainPostList.tsx
- src/pages/DetailFanPage.tsx
App.tsx url 작업
메인 페이지 최신글, 인기글 링크 작업
>
> Feat: 최신글, 인기글 링크 연결

- src/components/Profile/FollowBox.tsx
- src/components/Profile/FollowCard.tsx
- src/components/Profile/useGetUser.ts
- src/stores/refreshStore.ts
> feat: 팔로우 언팔로우 기능 추가

- src/components/FanPage/ThreadDetail.tsx
- src/components/FanPage/Threads.tsx
- src/components/FanPage/ThreadsList.tsx
- src/pages/DetailFanPage.tsx
> 게시물 상세보기 구현

- src/App.tsx
- src/components/Auth/EditProfile.tsx
- src/components/message/EmptyMessage.tsx
- src/components/message/MessageChatView.tsx
- src/components/message/MessageContainer.tsx
- src/components/message/MessageSidebar.tsx
- src/components/message/SendButton.tsx
- src/components/message/SendMessageForm.tsx
- src/components/message/SideMessageList.tsx
- src/layout/Header.tsx
- src/pages/MessagePage.tsx
- src/types/messageType.ts
쪽지함 사이드바에 유저와 쪽지 주고받은 목록 렌더링
쪽지 보내고 나면 사이드바에 가장 최근에 주고받은 목록이 상단에 뜨게 함.
그 외 css 수정
> feat: 쪽지함 사이드바 목록 렌더링

- src/components/Main/Highlight.tsx
> Fix: youtube 영상 갯수 수정

- src/components/FanPage/Threads.tsx
- src/components/FanPage/ThreadsList.tsx
- src/components/Profile/MyThreadsList.tsx
> feat: 포스트 삭제 기능 추가

- src/layout/Header.tsx
> Fix: 헤더 링크 이동 수정

- src/components/FanPage/ProfileBlock.tsx
- src/components/FanPage/Threads.tsx
- src/components/FanPage/Upload.tsx
> 게시글 업로드 api 호출

- src/App.tsx
- src/components/Auth/EditProfile.tsx
- src/components/Auth/inputValidation.ts
프로필 수정 페이지 url 유효성 검사, 이름 비밀번호 변경 기능, 사이드 바 유저 정보 기재
url로 넘어오는 유저 정보 id값으로 유효한 유저인지 검사 했는데 일반적으로 어떻게 검사하나요? jwt로 검사 해야하나요?
> 프로필 수정 페이지 url 유효성 검사, 이름 비밀번호 변경 기능, 사이드 바 유저 정보 기재

- src/components/FanPage/SimpleProfileCard.tsx
- src/components/FanPage/Threads.tsx
- src/components/Profile/FollowCard.tsx
- src/components/Profile/MyThreadsList.tsx
> feat: 프로필 페이지 수정 및 기능 추가

- src/components/message/MessageChatView.tsx
- src/components/message/SideMessageList.tsx
받은 메세지 자신이 읽음 처리는 사이드바 목록에서 ,
보낸 메세지 상대방 읽음 처리는 쪽지창 안쪽에서 보여지는 것으로 변경
> 쪽지 읽음처리 ui 수정

- src/components/message/MessageChatView.tsx
- src/components/message/NewMessageButton.tsx
- src/components/message/SendMessageForm.tsx
- src/components/message/SideMessageList.tsx
> 쪽지함 디자인 수정

- src/layout/RequireAuth.tsx
비로그인시 보이는 alert font size 조절
>
> Fix: Alert font size up

- src/components/message/MessageChatView.tsx
- src/components/message/NewMessageButton.tsx
- src/components/message/SendMessageForm.tsx
전송 버튼 클릭 시에 알림 api에도 전달되도록 설정했습니다.
> feat: 메세지 전송 시 알림 api 

- src/components/FanPage/Threads.tsx
- src/components/FanPage/ThreadsList.tsx
- src/components/Profile/EditPosts.tsx
- src/components/Profile/MyThreadsList.tsx
- 팬페이지 메인과 내 프로필 모두에서 게시글 수정이 가능합니다.
>
> feat: 포스트 수정 기능 구현

- src/components/FanPage/SimpleProfileCard.tsx
- src/components/Profile/EditPosts.tsx
- src/components/Profile/FollowCard.tsx
- src/layout/ProfileLayout.tsx
- 타 유저 프로필 페이지의 경우 쪽지함 및 프로필 수정 버튼이 보이지 않습니다.
- 팔로우 시 알림이 해당 유저에게 전송됩니다.
>
> feat: 프로필 페이지 디자인 수정 및 기능 추가

- src/api/axiosInstance.ts
- src/components/FanPage/ProfileBlock.tsx
- src/components/FanPage/ProfileImage.tsx
- src/components/FanPage/Threads.tsx
- src/components/FanPage/Upload.tsx
- src/components/Profile/FollowCard.tsx
- src/types/userTypes.ts
> 프로필 이미지 변경

- src/layout/RootLayout.tsx
> Fix: edit 페이지 공통 레이아웃 제거

- src/components/FanPage/Threads.tsx
- src/components/Profile/EditPosts.tsx
> fix: 빨간줄 오류 해결

- src/App.tsx
- src/layout/ProfileLayout.tsx
- 프로필 수정 페이지로 이동하는 path를 변경했습니다.
>
> fix: 프로필 수정 페이지 path 변경

- src/components/Header/HeaderIcon.tsx
- src/components/Header/NoticeBox.tsx
- src/components/Header/SearchBox.tsx
- src/components/Header/SearchThreads.tsx
- src/components/Header/SearchUser.tsx
- src/components/Header/ThreadRecommends.tsx
- src/components/Header/UserMenu.tsx
- src/components/Header/UserRecommend.tsx
- src/layout/Header.tsx
로그인/비로그인 시 보여지는 아이콘과 클릭 메뉴 수정
검색창 디자인 수정
추천, 검색 후 세부페이지 이동 path수정
> fix: 헤더 ui수정

- src/components/Profile/EditPosts.tsx
- src/components/Profile/MyThreadsList.tsx
- 좋아요 유지 에러 해결
- 수정 사항 반영된 thread로 보여지지 않는 에러 해결
>
> fix: 에러 해결

- src/layout/ProfileLayout.tsx
- 프로필 페이지에 응원하는 구단 마스코트를 연결했습니다.
>
> feat: 프로필 페이지 구단 마스코트 연결

- src/App.tsx
- src/layout/RootLayout.tsx
> Fix: message page Footer hide

- src/components/FanPage/SimpleProfileCard.tsx
- src/components/Profile/EditPosts.tsx
- simple profile card 스켈레톤 적용했습니다.
- simple profile card 긴 유저 네임을 ... 처리 했습니다.
- 프로필 수정 완료 시 버튼을 EDIT에서 수정완료로 변경했습니다.
>
> feat: simple profile card 스켈레톤 적용 및 긴 유저 네임 처리, 버튼 한글로 변경

- src/components/FanPage/Upload.tsx
> fix : 프로필 이름 설정

- src/components/Header/HeaderIcon.tsx
- src/components/Header/NoticeBox.tsx
알림 중 댓글, 좋아요 항목에 세부페이지로 이동하는 경로 오류로 수정 중에 있습니다.
> fix: 알림 클릭 시 세부페이지 오류

- src/layout/RootLayout.tsx
- src/pages/HomePage.tsx
메인페이지 제외 모든 페이지 Footer 제외
레이아웃 기본 디자인 h-full 로 수정
>
> Fix: Layout 수정

- src/components/Header/HeaderIcon.tsx
- src/components/Header/NoticeBox.tsx
- src/components/Header/SearchBox.tsx
- src/components/Header/UserMenu.tsx
- src/layout/Header.tsx
알림 목록 클릭 시 페이지 이동 경로 수정했습니다.
알림창에 좋아요, 댓글이 렌더링되지 않는 부분 수정했습니다.
팬페이지 active 상태 색상값 고정으로 추가했습니다.
> fix: 알림창 클릭시 해당페이지로 이동

- src/components/FanPage/SimpleProfileCard.tsx
- src/components/Profile/EditPosts.tsx
- src/components/Profile/FollowBox.tsx
- src/components/Profile/FollowCard.tsx
- src/components/Profile/MyThreadsList.tsx
- src/layout/ProfileLayout.tsx
- src/layout/RootLayout.tsx
- 쪽지함으로 이동은 하지만, 흰화면이 나오는 에러가 있습니다.
- 다크모드 스타일 수정했습니다.
- 게시물 날짜는 수정 날짜를 사용합니다.
- 팔로워 팔로잉 목록에서 쪽지 보내기 연결했습니다.
>
> feat: 다크모드 스타일 수정 및 게시물 수정 날짜 사용

- src/App.tsx
- src/components/message/MessageChatView.tsx
- src/components/message/SendButton.tsx
- src/components/message/SendMessageForm.tsx
- src/components/message/SideMessageList.tsx
- src/layout/RootLayout.tsx
- src/pages/MessagePage.tsx
> fix: message page ui수정

- src/layout/RootLayout.tsx
> Fix: layout 크기 수정

- src/components/Profile/FollowCard.tsx
- src/layout/ProfileLayout.tsx
- 타 유저 페이지에서 팔로우 팔로우 취소가 가능합니다.
- 프로필 페이지 헤더 스타일이 변경되었습니다.
>
> feat: 수정 사항 반영

- src/components/FanPage/Button.tsx
- src/components/FanPage/ThreadsList.tsx
- src/components/FanPage/Upload.tsx
제목, 내용이 없을 때 버튼 disabled 기능 추가
> 버튼 disabled

- src/components/Profile/FollowBox.tsx
- src/layout/ProfileLayout.tsx
- 프로필 페이지 마스코트 레이아웃이 변경되었습니다.
- 프로필 페이지의 TOP 버튼 색이 변경되었습니다.
- 타 유저 프로필 페이지의 팔로우 버튼에 기능이 추가되었습니다.
>
> feat: 프로필 페이지 레이아웃 수정 및 타 유저 프로필 팔로우 기능 추가

- src/components/Profile/MyThreadsList.tsx
- 게시물에서 createdAt 날짜를 사용합니다.
>
> feat: 게시물 createdAt 날짜 사용

- src/components/Header/HeaderIcon.tsx
- src/components/Header/NoticeBox.tsx
- src/components/Header/SearchBox.tsx
- src/components/Header/ThreadRecommends.tsx
- src/layout/Header.tsx
알림 읽음처리를 일괄 처리에서 개별처리로 수정했습니다.
> feat: 알림 읽음처리 개별읽음으로 수정

- src/components/Header/ThreadRecommends.tsx
- src/types/postType.ts
Header 검색에서 게시글 로드 오류 수정
Post 타입값 수정
>
> Fix: Header Search Error Fix

- src/layout/RootLayout.tsx
- src/pages/MessagePage.tsx
> Fix: layout 디자인 수정

- src/components/Header/SearchBox.tsx
> fix: 검색창 버튼디자인 수정

- src/components/Main/MainPostList.tsx
- src/components/Main/Ranking.tsx
- 경기 순위 -> 구단 순위
- 인기글/최신글 구단 이미지 크기 수정
>
> Fix: 텍스트 및 구단 로고 크기 변경

- src/components/Header/HeaderIcon.tsx
- src/components/Header/NoticeBox.tsx
- src/components/Header/SearchBox.tsx
- src/components/Header/ThreadRecommends.tsx
검색창 탭 디자인, 알림창 글씨 넘치는 부분 디자인 수정
> fix: 검색창, 알림창 디자인 수정

- src/components/Main/MainPostList.tsx
> Fix: 제목이 길 경우 생략 처리

- src/components/FanPage/SimpleProfileCard.tsx
- src/components/Profile/EditPosts.tsx
- src/components/Profile/FollowCard.tsx
- src/components/Profile/MyThreadsList.tsx
- src/layout/ProfileLayout.tsx
- username 없을 경우 "익명의 유저"로 표시
>
> feat: username 없을 경우 "익명의 유저"로 표시

- src/components/Header/NoticeBox.tsx
- src/components/Header/SearchThreads.tsx
- src/components/Header/SearchUser.tsx
- src/components/Header/ThreadRecommends.tsx
- src/components/Header/UserRecommend.tsx
- src/layout/Header.tsx
- src/types/postType.ts
검색창 추천게시글, 게시글 검색 결과에 넓이 초과 시 말줄임 표시
유저 검색 결과창 username으로 변경
알림 목록에 본인게시글에 본인 댓글 예외처리
> fix: 테스트 수정사항 수정

- src/components/message/MessageChatView.tsx
- src/components/message/MessageContainer.tsx
- src/components/message/NewMessage.tsx
- src/components/message/SideMessageList.tsx
- src/types/messageType.ts
username이 없다면 익명의 유저로 표기
이외 메세지창 margin값 조정
> fix: 메세지 창 username으로 변경

- src/components/Header/HeaderIcon.tsx
- src/components/Header/NoticeBox.tsx
알림 목록에서 목록에는 나오지 않으나 데이터상 자신이 제외되지 않는 현상으로 조건 수정했습니다.
> fix: 알림 목록 자신 제외

- src/components/FanPage/Sidebar.tsx
- src/components/FanPage/ThreadDetail.tsx
- src/components/FanPage/Upload.tsx
- src/layout/Header.tsx
게시글 상세페이지에서 scroll to top 추가
게시글 업로드 시 로딩창 구현
> 디테일 팬페이지 수정, 업로드 로딩창 추가

- src/components/Profile/EditPosts.tsx
- 수정시 제목 20자 이내만 입력할 수 있도록 처리
>
> feat: 수정시 제목 20자 이내만 입력할 수 있도록 처리

- src/layout/ProfileLayout.tsx
> feat: 쪽지함 숫자 제외

- src/components/FanPage/SimpleProfileCard.tsx
- simple profile card 프로필 이미지 cover로 수정
>
> fix: simple profile card 프로필 이미지 cover로 수정

- src/pages/HomePage.tsx
> Fix: 하이라이트 워터마크 디자인 수정

- src/components/Profile/EditPosts.tsx
- 게시글 수정 placeholder 변경했습니다.
- 게시글 수정시 내용 없는 경우 수정완료 disabled 되도록 변경했습니다.
>
> feat: 게시글 수정 placeholder 변경 및 내용 없는 경우 수정완료 disabled

- src/components/Auth/LogIn.tsx
로그인 아이디 저장 문구 수정
아이디 저장 -> 이메일 저장
>
> Fix: 로그인 페이지 문구 수정

- src/components/Message/MessageContainer.tsx
- src/components/Message/NewMessage.tsx
- src/components/Message/SendMessageForm.tsx
- src/components/Message/SideMessageList.tsx
SendMessageForm 위치 수정,
username만 검색 가능하도록 수정
placeholder 문구 수정
> 메세지함 수정사항 반영

- src/components/Main/MainPostGroup.tsx
> Fix: 스켈레톤 수정

- src/components/Message/MessageChatView.tsx
- src/components/Message/MessageContainer.tsx
- src/components/Message/NewMessage.tsx
- src/components/Message/SendMessageForm.tsx
- src/components/Message/SideMessageList.tsx
- src/pages/MessagePage.tsx
> 메세지함 테스트 수정사항 반영

- src/components/Header/SearchBox.tsx
- src/components/Header/SearchUser.tsx
- src/components/Header/ThreadRecommends.tsx
- src/components/Header/UserRecommend.tsx
> feat : 추천 게시글 api변경

- src/components/Auth/SelectClub.tsx
> 커버이미지 변경 기능 수정

- src/components/Message/SideMessageList.tsx
목록이 길어질 경우 스크롤이 안생기는 문제로 css 수정..
> fix: 사이드바 채팅 목록 css 수정

- src/components/Main/GameSchedule.tsx
- src/components/Main/MainPostGroup.tsx
> Fix: 디자인 디테일 수정

- src/components/FanPage/Threads.tsx
- src/components/FanPage/Upload.tsx
이미지 업로드 시 같은 파일일 경우 재 업이 안되는 버그 수정
상세 페이지에서 삭제 버튼 클릭 시 삭제된 게시글인지 알려주지 않음 -> 삭제 ui 구현
> 이미지 업로드 버그 수정 및 상세 페이지 삭제 UI 구현

- src/layout/Footer.tsx
> style: 푸터 문구 수정 및 디자인 수정

- src/components/FanPage/Sidebar.tsx
- src/components/FanPage/ThreadSkeleton.tsx
> Fix 스켈렛톤 수정, 사이드바 로고 이미지 크기 통일

- src/components/FanPage/Comments.tsx
- src/components/FanPage/ProfileImage.tsx
- src/components/Main/MainPostGroup.tsx
> Fix: API 로드 오류 수정

- src/api/notification.ts
> Route setting

- src/components/Main/MainPostList.tsx
문구 수정
제목이 없는 게시물 입니다. -> 제목 없음
>
> Fix: 문구 수정

- src/components/EditProfile/ProfileImage.tsx
- src/components/EditProfile/imageChange.ts
프로필 이미지 수정 할 때 이미지가 너무 늦게 변경 되는 부분 시각적으로 빠르게 전환 돼 보이도록 변경 했습니다.
> 프로필 이미지 수정 미리보기
